### ISSUE TITLE
does not run under virtualenv 

### ISSUE THREAD

**Issue by wesinator** [mandiant/stringsifter#12]
macOS 10.14.6
python 3.7.6 brew 

in a directory with spaces
https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/ 
`flarestrings file.exe`

`-bash: bad interpreter: No such file or directory`

**Comment by phtully** [comment]
thanks, @wesinator!

How did you set up your virtualenv?

From my local Mac, the following works fine:
```
virtualenv sifting
source sifting/bin/activate
(sifting) pip install stringsifter
(sifting) flarestrings file.exe
```

**Comment by wesinator** [comment]
> thanks, @wesinator!
> 
> How did you set up your virtualenv?
> 
> From my local Mac, the following works fine:
> 
> ```
> virtualenv sifting
> source sifting/bin/activate
> (sifting) pip install stringsifter
> (sifting) flarestrings file.exe
> ```

I ran `python3 -m venv env` per the python docs https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment 
`source env/bin/activate`

**Comment by phtully** [comment]
hi @wesinator, were you able to get this sorted out?

**Comment by ewalshfeye** [comment]
Can't reproduce this on macOS 10.14.6 with python 3.7.9 brew, libomp brew and stringsifter 1.20201201. Created a virtualenv in a directory with a space in the name, no issues

**Comment by ewalshmndt** [comment]
Still can't reproduce this on macOS 11.7.4 with python 3.9.17 and stringsifter 3.20230711. Created a virtualenv in a directory with a space in the name, no issues

Closing
