### ISSUE TITLE
stringsifter fails to install with pip 23.1

### ISSUE THREAD

**Issue by Ana06** [mandiant/stringsifter#29]
When I try to install stringsifter in Windows 10 with Python 8 and pip 23.1, I get the following error while installing the fasttext dependency
```
ModuleNotFoundError: No module named 'pybind11'
```

Using pip 20.1 solves the problem.

See https://github.com/facebookresearch/fastText/issues/512

**Comment by ewalshmndt** [comment]
Fixed by #34
