### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by Ana06** [mandiant/stringsifter#31]
scikit-learn 0.23 does not support Python 3.9: https://github.com/scikit-learn/scikit-learn/issues/18621
Updating to 0.24 should solve the issue.

**Comment by williballenthin** [comment]
stringsifter uses pickle to serialize their model, so it may not be easy to simply update the version string:

https://github.com/mandiant/stringsifter/tree/master/stringsifter/model

**Comment by ewalshmndt** [comment]
Fixed by #34
